<a href="https://colab.research.google.com/github/Fargus8866/Python/blob/main/arifmetik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import random as r
arr1=np.arange(8).reshape(2,4)
arr2=np.arange(4,12).reshape(2,4)

In [6]:
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
arr2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
arr1+arr2

array([[ 4,  6,  8, 10],
       [12, 14, 16, 18]])

In [9]:
arr1*arr2

array([[ 0,  5, 12, 21],
       [32, 45, 60, 77]])

In [10]:
arr1/arr2

array([[0.        , 0.2       , 0.33333333, 0.42857143],
       [0.5       , 0.55555556, 0.6       , 0.63636364]])

In [11]:
arr1-arr2

array([[-4, -4, -4, -4],
       [-4, -4, -4, -4]])

In [12]:
arr1**2

array([[ 0,  1,  4,  9],
       [16, 25, 36, 49]])

In [13]:
arr2**2

array([[ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [15]:
arr2**0.5

array([[2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])