<a href="https://colab.research.google.com/github/Fargus8866/Python/blob/main/chiziqli_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import random

In [3]:
x=np.random.randint(1,10,size=(2,3))
y=np.random.randint(1,10,size=(3,2))


In [4]:
x

array([[1, 5, 7],
       [2, 7, 2]])

In [5]:
y

array([[5, 9],
       [8, 1],
       [6, 2]])

In [6]:
x.dot(y)

array([[87, 28],
       [78, 29]])

In [7]:
np.dot(x,y)

array([[87, 28],
       [78, 29]])

In [8]:
y.dot(x)

array([[23, 88, 53],
       [10, 47, 58],
       [10, 44, 46]])

In [9]:
np.dot(y,x)

array([[23, 88, 53],
       [10, 47, 58],
       [10, 44, 46]])