<a href="https://colab.research.google.com/github/Fargus8866/Python/blob/main/fayllar_bilan_ishlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random


In [2]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('data',arr)

In [4]:
arr2=np.load('data.npy')
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1=np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
np.savez('arrays',a=arr2,b=arr1)

In [7]:
arrays=np.load('arrays.npz')


In [8]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
arrays['a'][:7]

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
arrays['b'][3:14]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [17]:
np.savez_compressed('compressed_arrays',a=arr2,b=arr1)

In [18]:
carrays=np.load('compressed_arrays.npz')


In [19]:
carrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
carrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])