<a href="https://colab.research.google.com/github/Fargus8866/Python/blob/main/matematik_va_statik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import random
arr=np.random.randn(4,5)
arr

array([[ 1.28591869, -0.56508515,  1.77261986,  0.81548851,  0.33497834],
       [-0.51461564, -0.84372061, -0.0507646 ,  0.7452508 , -0.2770756 ],
       [ 0.77472484, -1.36876523,  2.01762405,  0.51609092, -0.55824505],
       [ 0.20578279,  0.73469164, -0.83845253,  0.41823911,  0.16206777]])

In [3]:
arr.sum()

4.766752912990504

In [5]:
arr.sum(axis=1,)

array([ 3.64392025, -0.94092564,  1.38142953,  0.68232877])

In [6]:
arr.sum(axis=0)

array([ 1.75181068, -2.04287935,  2.90102678,  2.49506934, -0.33827454])

In [7]:
np.mean(arr)

0.2383376456495252

In [8]:
arr.mean(axis=1)

array([ 0.72878405, -0.18818513,  0.27628591,  0.13646575])

In [9]:
arr.mean(axis=0)

array([ 0.43795267, -0.51071984,  0.72525669,  0.62376734, -0.08456864])

In [10]:
np.mean(arr,axis=1)

array([ 0.72878405, -0.18818513,  0.27628591,  0.13646575])

In [13]:
arr2=np.arange(6)

In [15]:
arr2

array([0, 1, 2, 3, 4, 5])

In [16]:
arr2.cumsum()

array([ 0,  1,  3,  6, 10, 15])