<a href="https://colab.research.google.com/github/Fargus8866/Python/blob/pandas/PandasDataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [9]:
data={
    'yil':[2019,2020,2021,2022,2023,2024],
    'aholi_soni':['31 M','32 M','33 M','34 M','35 M','36 M'],
    'temp':[16.7,18.9,14.5,7.9,15.3,20.1]
}
df = pd.DataFrame(data)

In [10]:
df=pd.DataFrame(data,columns=['yil','temp','aholi_soni'])

In [11]:
df

yil  temp aholi_soni
0  2019  16.7       31 M
1  2020  18.9       32 M
2  2021  14.5       33 M
3  2022   7.9       34 M
4  2023  15.3       35 M
5  2024  20.1       36 M

In [12]:
df=pd.DataFrame(data,columns=['yil','temp','aholi_soni','YaIM'])

In [13]:
df

yil  temp aholi_soni YaIM
0  2019  16.7       31 M  NaN
1  2020  18.9       32 M  NaN
2  2021  14.5       33 M  NaN
3  2022   7.9       34 M  NaN
4  2023  15.3       35 M  NaN
5  2024  20.1       36 M  NaN

In [14]:
df.yil

0    2019
1    2020
2    2021
3    2022
4    2023
5    2024
Name: yil, dtype: int64

In [15]:
df=pd.DataFrame(data,columns=['yil','temp','aholi_soni','YaIM'],index=[15,16,17,18,19,20])

In [16]:
df

yil  temp aholi_soni YaIM
15  2019  16.7       31 M  NaN
16  2020  18.9       32 M  NaN
17  2021  14.5       33 M  NaN
18  2022   7.9       34 M  NaN
19  2023  15.3       35 M  NaN
20  2024  20.1       36 M  NaN

In [17]:
df.index

Int64Index([15, 16, 17, 18, 19, 20], dtype='int64')

In [18]:
df=pd.DataFrame(data,columns=['yil','temp','aholi_soni','YaIM'],index=[15,16,17,18,19,20])

In [19]:
df

yil  temp aholi_soni YaIM
15  2019  16.7       31 M  NaN
16  2020  18.9       32 M  NaN
17  2021  14.5       33 M  NaN
18  2022   7.9       34 M  NaN
19  2023  15.3       35 M  NaN
20  2024  20.1       36 M  NaN

In [20]:
df.YaIM=0

In [21]:
df

yil  temp aholi_soni  YaIM
15  2019  16.7       31 M     0
16  2020  18.9       32 M     0
17  2021  14.5       33 M     0
18  2022   7.9       34 M     0
19  2023  15.3       35 M     0
20  2024  20.1       36 M     0

In [22]:
val=pd.Series([150,280,695],index=[16,18,19])
df.YaIM=val
df

yil  temp aholi_soni   YaIM
15  2019  16.7       31 M    NaN
16  2020  18.9       32 M  150.0
17  2021  14.5       33 M    NaN
18  2022   7.9       34 M  280.0
19  2023  15.3       35 M  695.0
20  2024  20.1       36 M    NaN

In [23]:
df['+ or -']=df.YaIM >150
df

yil  temp aholi_soni   YaIM  + or -
15  2019  16.7       31 M    NaN   False
16  2020  18.9       32 M  150.0   False
17  2021  14.5       33 M    NaN   False
18  2022   7.9       34 M  280.0    True
19  2023  15.3       35 M  695.0    True
20  2024  20.1       36 M    NaN   False

In [24]:
del df['+ or -']

In [25]:
df

yil  temp aholi_soni   YaIM
15  2019  16.7       31 M    NaN
16  2020  18.9       32 M  150.0
17  2021  14.5       33 M    NaN
18  2022   7.9       34 M  280.0
19  2023  15.3       35 M  695.0
20  2024  20.1       36 M    NaN

In [26]:
data1 = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}

In [27]:
df2=pd.DataFrame(data1)

In [28]:
df2

Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [29]:
df2.index.name='Yil'

In [30]:
df2

Uzbekistan  Kazakhstan
Yil                         
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [31]:
df2.T

Yil         2021  2020  2019  2018  2017  2016
Uzbekistan  33.9  33.5  32.9  32.5  31.9   NaN
Kazakhstan  18.9  18.7  18.5  18.3  18.1  17.8

In [32]:
df2=df2.T

In [33]:
df2

Yil         2021  2020  2019  2018  2017  2016
Uzbekistan  33.9  33.5  32.9  32.5  31.9   NaN
Kazakhstan  18.9  18.7  18.5  18.3  18.1  17.8

In [34]:
df2.index

Index(['Uzbekistan', 'Kazakhstan'], dtype='object')

In [35]:
df2.values

array([[33.9, 33.5, 32.9, 32.5, 31.9,  nan],
       [18.9, 18.7, 18.5, 18.3, 18.1, 17.8]])

In [36]:
df2[2016]

Uzbekistan     NaN
Kazakhstan    17.8
Name: 2016, dtype: float64

In [37]:
del df2[2016]

In [38]:
df2

Yil         2021  2020  2019  2018  2017
Uzbekistan  33.9  33.5  32.9  32.5  31.9
Kazakhstan  18.9  18.7  18.5  18.3  18.1

In [39]:
df2=df2.T

In [40]:
df2

Uzbekistan  Kazakhstan
Yil                         
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1

In [41]:
usernames={
    'anvar':'anvarjon1525',
    'doston':'doston8866',
    'sherzod':'sher1996',
    'diyor':'diyor1555',
    'kamron':'fargus1456'
}
email={
    'anvar':'anvarjon@mail.ru',
    'doston':'doston.rahimov.97@bk.ru',
    'sherzod':'sherzod96@gmail.com',
    'diyor':'diyorahimov@mail.ru',
    'kamron':'fargus@bk.ru'
}
data={
    'username':usernames,
    'email':email
}

In [42]:
df=pd.DataFrame(data)

In [43]:
df.index.name='ismlar'

In [44]:
df

username                    email
ismlar                                        
anvar    anvarjon1525         anvarjon@mail.ru
doston     doston8866  doston.rahimov.97@bk.ru
sherzod      sher1996      sherzod96@gmail.com
diyor       diyor1555      diyorahimov@mail.ru
kamron     fargus1456             fargus@bk.ru

In [45]:
data2={
    'username':{
        'olim':'olimjon',
        'tolib':'tolibjon',
        'doston':'dostonboy',
        'sherzod':'sherzodboy'
    },
    'email':{
        'olim':'olimjon@mail.ru',
        'tolib':'tolibjon@bk.ru',
        'doston':'dostonboy@list.ru',
        'sherzod':'sherzodboy@gmail.com'
    }
}


In [46]:
df2=df.append(pd.DataFrame(data2))
df2.index.name='ismlar'
df2

<ipython-input-46-6afd6a66d2c6>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df.append(pd.DataFrame(data2))


username                    email
ismlar                                        
anvar    anvarjon1525         anvarjon@mail.ru
doston     doston8866  doston.rahimov.97@bk.ru
sherzod      sher1996      sherzod96@gmail.com
diyor       diyor1555      diyorahimov@mail.ru
kamron     fargus1456             fargus@bk.ru
olim          olimjon          olimjon@mail.ru
tolib        tolibjon           tolibjon@bk.ru
doston      dostonboy        dostonboy@list.ru
sherzod    sherzodboy     sherzodboy@gmail.com

In [47]:
arr=df2.username

In [48]:
arr

ismlar
anvar      anvarjon1525
doston       doston8866
sherzod        sher1996
diyor         diyor1555
kamron       fargus1456
olim            olimjon
tolib          tolibjon
doston        dostonboy
sherzod      sherzodboy
Name: username, dtype: object

In [49]:
df2.index

Index(['anvar', 'doston', 'sherzod', 'diyor', 'kamron', 'olim', 'tolib',
       'doston', 'sherzod'],
      dtype='object', name='ismlar')

In [50]:
newind=pd.Index(['olim','doston','hamida','shix'])

In [51]:
newind.isin(df2.index)

array([ True,  True, False, False])

In [52]:
df2.index.isin(newind)

array([False,  True, False, False, False,  True, False,  True, False])

In [53]:
newind.difference(df2.index)

Index(['hamida', 'shix'], dtype='object')

In [54]:
df2.index.difference(newind)

Index(['anvar', 'diyor', 'kamron', 'sherzod', 'tolib'], dtype='object')

In [55]:
df2.index.union(newind)

Index(['anvar', 'diyor', 'doston', 'doston', 'hamida', 'kamron', 'olim',
       'sherzod', 'sherzod', 'shix', 'tolib'],
      dtype='object')

In [56]:
df2

username                    email
ismlar                                        
anvar    anvarjon1525         anvarjon@mail.ru
doston     doston8866  doston.rahimov.97@bk.ru
sherzod      sher1996      sherzod96@gmail.com
diyor       diyor1555      diyorahimov@mail.ru
kamron     fargus1456             fargus@bk.ru
olim          olimjon          olimjon@mail.ru
tolib        tolibjon           tolibjon@bk.ru
doston      dostonboy        dostonboy@list.ru
sherzod    sherzodboy     sherzodboy@gmail.com

In [57]:
arr=df2.index.delete(0)

In [58]:
arr

Index(['doston', 'sherzod', 'diyor', 'kamron', 'olim', 'tolib', 'doston',
       'sherzod'],
      dtype='object', name='ismlar')

In [59]:
df2.T

ismlar               anvar                   doston              sherzod  \
username      anvarjon1525               doston8866             sher1996   
email     anvarjon@mail.ru  doston.rahimov.97@bk.ru  sherzod96@gmail.com   

ismlar                  diyor        kamron             olim           tolib  \
username            diyor1555    fargus1456          olimjon        tolibjon   
email     diyorahimov@mail.ru  fargus@bk.ru  olimjon@mail.ru  tolibjon@bk.ru   

ismlar               doston               sherzod  
username          dostonboy            sherzodboy  
email     dostonboy@list.ru  sherzodboy@gmail.com

In [60]:
df2.T.doston

ismlar                     doston             doston
username               doston8866          dostonboy
email     doston.rahimov.97@bk.ru  dostonboy@list.ru

In [61]:
df2

username                    email
ismlar                                        
anvar    anvarjon1525         anvarjon@mail.ru
doston     doston8866  doston.rahimov.97@bk.ru
sherzod      sher1996      sherzod96@gmail.com
diyor       diyor1555      diyorahimov@mail.ru
kamron     fargus1456             fargus@bk.ru
olim          olimjon          olimjon@mail.ru
tolib        tolibjon           tolibjon@bk.ru
doston      dostonboy        dostonboy@list.ru
sherzod    sherzodboy     sherzodboy@gmail.com

In [62]:
df2.index.unique()

Index(['anvar', 'doston', 'sherzod', 'diyor', 'kamron', 'olim', 'tolib'], dtype='object', name='ismlar')

In [70]:
df2.index = df2.index.map(lambda x: x.title())
df2.columns=df2.columns.map(lambda x: x.title())


In [75]:
df2

Username                    Email
ismlar                                        
Anvar    anvarjon1525         anvarjon@mail.ru
Doston     doston8866  doston.rahimov.97@bk.ru
Sherzod      sher1996      sherzod96@gmail.com
Diyor       diyor1555      diyorahimov@mail.ru
Kamron     fargus1456             fargus@bk.ru
Olim          olimjon          olimjon@mail.ru
Tolib        tolibjon           tolibjon@bk.ru
Doston      dostonboy        dostonboy@list.ru
Sherzod    sherzodboy     sherzodboy@gmail.com