<a href="https://colab.research.google.com/github/Fargus8866/Python/blob/main/shart_operatori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import random
arr=np.random.randint(1,100,size=(5,3))


[[51 42 90]
 [ 6 60 57]
 [48 13 83]
 [42 47 97]
 [47 25 72]]
[[51 42 90]
 [ 6 60 57]]


In [15]:
arr1=np.array(['doston','Sherzod','hamro','Diyor'])
for i in arr1:
  if i.title()==i:
    print(i)
  else:
    print(i.title())


Doston
Sherzod
Hamro
Diyor


In [16]:
arr2=np.random.randn(4,5)
arr2

array([[ 1.18457342,  0.90440816, -0.25214628, -0.9056688 ,  0.18348602],
       [ 1.65642214, -0.28839792, -0.67915108,  1.40762595,  1.10703902],
       [-1.52375686, -0.64483803,  1.55009903, -1.02265849, -0.13174959],
       [ 0.07038193, -0.55357936, -0.56330372,  1.59867909, -0.10198034]])

In [17]:
res=np.where(arr2<0,arr2+1,arr2-1)
res

array([[ 0.18457342, -0.09559184,  0.74785372,  0.0943312 , -0.81651398],
       [ 0.65642214,  0.71160208,  0.32084892,  0.40762595,  0.10703902],
       [-0.52375686,  0.35516197,  0.55009903, -0.02265849,  0.86825041],
       [-0.92961807,  0.44642064,  0.43669628,  0.59867909,  0.89801966]])