<a href="https://colab.research.google.com/github/Fargus8866/Python/blob/main/sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

In [2]:
data=np.random.randn(5)
data

array([ 0.81265284, -0.06258952,  0.23123366, -0.25215622, -0.22618557])

In [4]:
np.sort(data)

array([-0.25215622, -0.22618557, -0.06258952,  0.23123366,  0.81265284])

In [5]:
data.sort()
data

array([-0.25215622, -0.22618557, -0.06258952,  0.23123366,  0.81265284])

In [6]:
arr=-np.sort(-data)
arr

array([ 0.81265284,  0.23123366, -0.06258952, -0.22618557, -0.25215622])

In [8]:
arr2d=np.random.randint(1,100,size=(2,4))
arr2d

array([[81,  2, 46, 31],
       [ 3, 36, 14, 17]])

In [9]:
np.sort(arr2d,axis=1)

array([[ 2, 31, 46, 81],
       [ 3, 14, 17, 36]])

In [10]:
np.sort(arr2d,axis=0)

array([[ 3,  2, 14, 17],
       [81, 36, 46, 31]])